[2024-09-02T22:22:49.024Z] info: docker.yaml was copied to the config folder
[2024-09-02T22:22:49.029Z] info: services.yaml was copied to the config folder
[2024-09-02T22:22:49.032Z] info: bookmarks.yaml was copied to the config folder
[2024-09-02T22:22:49.050Z] info: widgets.yaml was copied to the config folder
[2024-09-02T22:22:49.052Z] info: custom.css was copied to the config folder
[2024-09-02T22:22:49.055Z] info: custom.js was copied to the config folder
[2024-09-02T22:22:49.390Z] info: kubernetes.yaml was copied to the config folder
[2024-09-03T19:47:15.354Z] error: Failed to load services.yaml, please check for errors
[2024-09-03T19:47:15.358Z] error: TypeError: servicesGroup[Object.keys(...)[0]].map is not a function
[2024-09-03T19:47:15.400Z] error: Failed to load services.yaml, please check for errors
[2024-09-03T19:47:15.403Z] error: TypeError: servicesGroup[Object.keys(...)[0]].map is not a function
[2024-09-03T19:47:15.968Z] error: Failed to load services.yaml, please check for errors
[2024-09-03T19:47:15.971Z] error: TypeError: servicesGroup[Object.keys(...)[0]].map is not a function
[2024-09-04T10:22:00.356Z] error: Failed to load services.yaml, please check for errors
[2024-09-04T10:22:00.360Z] error: YAMLException: bad indentation of a sequence entry (11:13)

  8 |         description: Homepage is awesome
  9 | 
 10 |     - TrueNAS
 11 |         type: truenas
------------------^
 12 |         url: http://10.1.1.10
 13 |         key: 1-V6pC74RImZLFL1X228CAMMAUfXE7 ...
[2024-09-04T10:22:00.370Z] error: Failed to load services.yaml, please check for errors
[2024-09-04T10:22:00.371Z] error: YAMLException: bad indentation of a sequence entry (11:13)

  8 |         description: Homepage is awesome
  9 | 
 10 |     - TrueNAS
 11 |         type: truenas
------------------^
 12 |         url: http://10.1.1.10
 13 |         key: 1-V6pC74RImZLFL1X228CAMMAUfXE7 ...
[2024-09-04T10:22:01.018Z] error: Failed to load services.yaml, please check for errors
[2024-09-04T10:22:01.019Z] error: YAMLException: bad indentation of a sequence entry (11:13)

  8 |         description: Homepage is awesome
  9 | 
 10 |     - TrueNAS
 11 |         type: truenas
------------------^
 12 |         url: http://10.1.1.10
 13 |         key: 1-V6pC74RImZLFL1X228CAMMAUfXE7 ...
[2024-09-04T10:22:42.539Z] error: Failed to load widgets, please check widgets.yaml for errors or remove example entries.
[2024-09-04T10:22:42.542Z] error: end of the stream or a document separator is expected (23:1)

 20 |         format:
 21 |                 maximumFraction ...
 22 | 
 23 | widget:
------^
 24 |    
 25 |         type: truenas
[2024-09-04T10:22:42.604Z] error: Failed to load widgets, please check widgets.yaml for errors or remove example entries.
[2024-09-04T10:22:42.607Z] error: end of the stream or a document separator is expected (23:1)

 20 |         format:
 21 |                 maximumFraction ...
 22 | 
 23 | widget:
------^
 24 |    
 25 |         type: truenas
[2024-09-04T10:22:42.869Z] error: Failed to load widgets, please check widgets.yaml for errors or remove example entries.
[2024-09-04T10:22:42.871Z] error: end of the stream or a document separator is expected (23:1)

 20 |         format:
 21 |                 maximumFraction ...
 22 | 
 23 | widget:
------^
 24 |    
 25 |         type: truenas
[2024-09-04T10:23:30.292Z] error: Failed to load services.yaml, please check for errors
[2024-09-04T10:23:30.293Z] error: YAMLException: end of the stream or a document separator is expected (23:1)

 20 |         description: Homepage is ðŸ˜Ž
 21 | 
 22 | 
 23 | widget:
------^
 24 |    
 25 |         type: truenas
[2024-09-04T10:23:30.298Z] error: Failed to load services.yaml, please check for errors
[2024-09-04T10:23:30.299Z] error: YAMLException: end of the stream or a document separator is expected (23:1)

 20 |         description: Homepage is ðŸ˜Ž
 21 | 
 22 | 
 23 | widget:
------^
 24 |    
 25 |         type: truenas
[2024-09-04T10:23:30.706Z] error: Failed to load services.yaml, please check for errors
[2024-09-04T10:23:30.707Z] error: YAMLException: end of the stream or a document separator is expected (23:1)

 20 |         description: Homepage is ðŸ˜Ž
 21 | 
 22 | 
 23 | widget:
------^
 24 |    
 25 |         type: truenas
[2024-09-04T10:23:36.840Z] error: Failed to load services.yaml, please check for errors
[2024-09-04T10:23:36.841Z] error: YAMLException: end of the stream or a document separator is expected (23:1)

 20 |         description: Homepage is ðŸ˜Ž
 21 | 
 22 | 
 23 | widget:
------^
 24 |         type: truenas
 25 |         url: http://10.1.1.10
[2024-09-04T10:24:19.440Z] error: Failed to load services.yaml, please check for errors
[2024-09-04T10:24:19.442Z] error: TypeError: servicesGroup[Object.keys(...)[0]].map is not a function
[2024-09-04T10:24:19.887Z] error: Failed to load services.yaml, please check for errors
[2024-09-04T10:24:19.890Z] error: TypeError: servicesGroup[Object.keys(...)[0]].map is not a function
[2024-09-04T12:33:46.510Z] error: Failed to load services.yaml, please check for errors
[2024-09-04T12:33:46.512Z] error: TypeError: servicesGroup[Object.keys(...)[0]].map is not a function
[2024-09-04T12:33:46.519Z] error: Failed to load services.yaml, please check for errors
[2024-09-04T12:33:46.519Z] error: TypeError: servicesGroup[Object.keys(...)[0]].map is not a function
[2024-09-04T12:33:47.290Z] error: Failed to load services.yaml, please check for errors
[2024-09-04T12:33:47.292Z] error: TypeError: servicesGroup[Object.keys(...)[0]].map is not a function
[2024-09-04T12:34:00.412Z] error: Failed to load services.yaml, please check for errors
[2024-09-04T12:34:00.413Z] error: TypeError: servicesGroup[Object.keys(...)[0]].map is not a function
[2024-09-04T12:35:05.779Z] error: Failed to load services.yaml, please check for errors
[2024-09-04T12:35:05.780Z] error: TypeError: servicesGroup[Object.keys(...)[0]].map is not a function
[2024-09-04T12:35:05.783Z] error: Failed to load services.yaml, please check for errors
[2024-09-04T12:35:05.784Z] error: TypeError: servicesGroup[Object.keys(...)[0]].map is not a function
[2024-09-04T12:35:06.147Z] error: Failed to load services.yaml, please check for errors
[2024-09-04T12:35:06.149Z] error: TypeError: servicesGroup[Object.keys(...)[0]].map is not a function
[2024-09-04T12:36:05.001Z] error: Failed to load services.yaml, please check for errors
[2024-09-04T12:36:05.007Z] error: TypeError: servicesGroup[Object.keys(...)[0]].map is not a function
[2024-09-04T12:36:05.669Z] error: Failed to load services.yaml, please check for errors
[2024-09-04T12:36:05.671Z] error: TypeError: servicesGroup[Object.keys(...)[0]].map is not a function
[2024-09-04T12:36:22.337Z] error: Failed to load services.yaml, please check for errors
[2024-09-04T12:36:22.339Z] error: TypeError: servicesGroup[Object.keys(...)[0]].map is not a function
[2024-09-04T12:36:24.265Z] error: Failed to load services.yaml, please check for errors
[2024-09-04T12:36:24.267Z] error: TypeError: servicesGroup[Object.keys(...)[0]].map is not a function
[2024-09-04T12:36:31.790Z] error: Failed to load services.yaml, please check for errors
[2024-09-04T12:36:31.792Z] error: TypeError: servicesGroup[Object.keys(...)[0]].map is not a function
[2024-09-04T12:40:49.377Z] error: Failed to discover services, please check kubernetes.yaml for errors or remove example entries.
[2024-09-04T12:40:49.380Z] error: YAMLException: bad indentation of a mapping entry (11:7)

  8 | 
  9 | background:
 10 |   image:https://images-wixmp-ed30a86b ...
 11 |   blur: sm # sm, "", md, xl... see ht ...
------------^
 12 |   saturate: 50 # 0, 50, 100... see ht ...
 13 |   brightness: 50 # 0, 50, 75... see h ...
[2024-09-04T12:40:49.389Z] error: Failed to load settings.yaml, please check for errors
[2024-09-04T12:40:49.391Z] error: YAMLException: bad indentation of a mapping entry (11:7)

  8 | 
  9 | background:
 10 |   image:https://images-wixmp-ed30a86b ...
 11 |   blur: sm # sm, "", md, xl... see ht ...
------------^
 12 |   saturate: 50 # 0, 50, 100... see ht ...
 13 |   brightness: 50 # 0, 50, 75... see h ...
[2024-09-04T12:40:49.429Z] error: <index> YAMLException: bad indentation of a mapping entry (11:7)

  8 | 
  9 | background:
 10 |   image:https://images-wixmp-ed30a86b ...
 11 |   blur: sm # sm, "", md, xl... see ht ...
------------^
 12 |   saturate: 50 # 0, 50, 100... see ht ...
 13 |   brightness: 50 # 0, 50, 75... see h ...
    at generateError (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:1273:10)
    at throwError (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:1277:9)
    at readBlockMapping (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2272:7)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2531:12)
    at readDocument (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2715:3)
    at loadDocuments (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2778:5)
    at Object.load$1 [as load] (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2804:19)
    at getSettings (/app/.next/server/chunks/1167.js:109:75)
    at getStaticProps (/app/.next/server/pages/index.js:3068:101)
    at Object.renderToHTML (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.3.1__react@18.3.1/node_modules/next/dist/server/render.js:386:26)
[2024-09-04T12:40:49.474Z] error: Failed to load settings.yaml, please check for errors
[2024-09-04T12:40:49.476Z] error: YAMLException: bad indentation of a mapping entry (11:7)

  8 | 
  9 | background:
 10 |   image:https://images-wixmp-ed30a86b ...
 11 |   blur: sm # sm, "", md, xl... see ht ...
------------^
 12 |   saturate: 50 # 0, 50, 100... see ht ...
 13 |   brightness: 50 # 0, 50, 75... see h ...
[2024-09-04T12:40:49.829Z] error: Failed to discover services, please check kubernetes.yaml for errors or remove example entries.
[2024-09-04T12:40:49.829Z] error: YAMLException: bad indentation of a mapping entry (11:7)

  8 | 
  9 | background:
 10 |   image:https://images-wixmp-ed30a86b ...
 11 |   blur: sm # sm, "", md, xl... see ht ...
------------^
 12 |   saturate: 50 # 0, 50, 100... see ht ...
 13 |   brightness: 50 # 0, 50, 75... see h ...
[2024-09-04T12:40:49.832Z] error: Failed to load settings.yaml, please check for errors
[2024-09-04T12:40:49.833Z] error: YAMLException: bad indentation of a mapping entry (11:7)

  8 | 
  9 | background:
 10 |   image:https://images-wixmp-ed30a86b ...
 11 |   blur: sm # sm, "", md, xl... see ht ...
------------^
 12 |   saturate: 50 # 0, 50, 100... see ht ...
 13 |   brightness: 50 # 0, 50, 75... see h ...
[2024-09-04T12:40:49.839Z] error: Failed to load settings.yaml, please check for errors
[2024-09-04T12:40:49.840Z] error: YAMLException: bad indentation of a mapping entry (11:7)

  8 | 
  9 | background:
 10 |   image:https://images-wixmp-ed30a86b ...
 11 |   blur: sm # sm, "", md, xl... see ht ...
------------^
 12 |   saturate: 50 # 0, 50, 100... see ht ...
 13 |   brightness: 50 # 0, 50, 75... see h ...
[2024-09-04T13:54:15.783Z] error: Failed to load services.yaml, please check for errors
[2024-09-04T13:54:15.791Z] error: TypeError: Cannot read properties of null (reading 'map')
[2024-09-04T13:54:15.804Z] error: Failed to load services.yaml, please check for errors
[2024-09-04T13:54:15.804Z] error: TypeError: Cannot read properties of null (reading 'map')
[2024-09-04T13:54:17.090Z] error: Failed to load services.yaml, please check for errors
[2024-09-04T13:54:17.091Z] error: TypeError: Cannot read properties of null (reading 'map')
[2024-09-04T13:54:29.306Z] error: Failed to load services.yaml, please check for errors
[2024-09-04T13:54:29.309Z] error: TypeError: Cannot read properties of null (reading 'map')
[2024-09-04T14:14:24.242Z] error: <credentialedProxyHandler> HTTP Error 404 calling https://api.tailscale.com/api/v2/device/deviceid
[2024-09-04T14:15:42.375Z] error: <credentialedProxyHandler> HTTP Error 404 calling https://api.tailscale.com/api/v2/device/kzDRogSQnC11CNTRL
[2024-09-04T14:15:55.610Z] error: <credentialedProxyHandler> HTTP Error 404 calling https://api.tailscale.com/api/v2/device/kzDRogSQnC11CNTRL
[2024-09-04T14:16:47.641Z] error: <credentialedProxyHandler> HTTP Error 404 calling https://api.tailscale.com/api/v2/device/kzDRogSQnC11CNTRL
[2024-09-04T14:23:34.493Z] error: <servicesProxy> TypeError: Cannot read properties of null (reading 'map')
    at /app/.next/server/chunks/5318.js:124:60
    at Array.map (<anonymous>)
    at servicesFromConfig (/app/.next/server/chunks/5318.js:122:34)
    at async getServiceItem (/app/.next/server/chunks/5318.js:682:30)
    at async getServiceWidget (/app/.next/server/chunks/5318.js:709:23)
    at async handler (/app/.next/server/pages/api/services/proxy.js:402:27)
    at async Object.apiResolver (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.3.1__react@18.3.1/node_modules/next/dist/server/api-utils/node.js:366:9)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:481:9)
    at async Object.fn (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:741:37)
    at async Router.execute (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.3.1__react@18.3.1/node_modules/next/dist/server/router.js:252:36)
[2024-09-04T14:23:34.501Z] error: <servicesProxy> TypeError: Cannot read properties of null (reading 'map')
    at /app/.next/server/chunks/5318.js:124:60
    at Array.map (<anonymous>)
    at servicesFromConfig (/app/.next/server/chunks/5318.js:122:34)
    at async getServiceItem (/app/.next/server/chunks/5318.js:682:30)
    at async getServiceWidget (/app/.next/server/chunks/5318.js:709:23)
    at async handler (/app/.next/server/pages/api/services/proxy.js:402:27)
    at async Object.apiResolver (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.3.1__react@18.3.1/node_modules/next/dist/server/api-utils/node.js:366:9)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:481:9)
    at async Object.fn (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:741:37)
    at async Router.execute (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.3.1__react@18.3.1/node_modules/next/dist/server/router.js:252:36)
[2024-09-04T14:23:34.506Z] error: <servicesProxy> TypeError: Cannot read properties of null (reading 'map')
    at /app/.next/server/chunks/5318.js:124:60
    at Array.map (<anonymous>)
    at servicesFromConfig (/app/.next/server/chunks/5318.js:122:34)
    at async getServiceItem (/app/.next/server/chunks/5318.js:682:30)
    at async getServiceWidget (/app/.next/server/chunks/5318.js:709:23)
    at async handler (/app/.next/server/pages/api/services/proxy.js:402:27)
    at async Object.apiResolver (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.3.1__react@18.3.1/node_modules/next/dist/server/api-utils/node.js:366:9)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:481:9)
    at async Object.fn (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:741:37)
    at async Router.execute (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.3.1__react@18.3.1/node_modules/next/dist/server/router.js:252:36)
[2024-09-04T14:23:34.508Z] error: <servicesProxy> TypeError: Cannot read properties of null (reading 'map')
    at /app/.next/server/chunks/5318.js:124:60
    at Array.map (<anonymous>)
    at servicesFromConfig (/app/.next/server/chunks/5318.js:122:34)
    at async getServiceItem (/app/.next/server/chunks/5318.js:682:30)
    at async getServiceWidget (/app/.next/server/chunks/5318.js:709:23)
    at async handler (/app/.next/server/pages/api/services/proxy.js:402:27)
    at async Object.apiResolver (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.3.1__react@18.3.1/node_modules/next/dist/server/api-utils/node.js:366:9)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:481:9)
    at async Object.fn (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:741:37)
    at async Router.execute (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.3.1__react@18.3.1/node_modules/next/dist/server/router.js:252:36)
[2024-09-04T14:23:34.541Z] error: <servicesProxy> TypeError: Cannot read properties of null (reading 'map')
    at /app/.next/server/chunks/5318.js:124:60
    at Array.map (<anonymous>)
    at servicesFromConfig (/app/.next/server/chunks/5318.js:122:34)
    at async getServiceItem (/app/.next/server/chunks/5318.js:682:30)
    at async getServiceWidget (/app/.next/server/chunks/5318.js:709:23)
    at async handler (/app/.next/server/pages/api/services/proxy.js:402:27)
    at async Object.apiResolver (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.3.1__react@18.3.1/node_modules/next/dist/server/api-utils/node.js:366:9)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:481:9)
    at async Object.fn (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:741:37)
    at async Router.execute (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.3.1__react@18.3.1/node_modules/next/dist/server/router.js:252:36)
[2024-09-04T14:23:34.551Z] error: Failed to load services.yaml, please check for errors
[2024-09-04T14:23:34.553Z] error: TypeError: Cannot read properties of null (reading 'map')
[2024-09-04T14:23:34.558Z] error: Failed to load services.yaml, please check for errors
[2024-09-04T14:23:34.559Z] error: TypeError: Cannot read properties of null (reading 'map')
[2024-09-04T14:23:34.892Z] error: Failed to load services.yaml, please check for errors
[2024-09-04T14:23:34.894Z] error: TypeError: Cannot read properties of null (reading 'map')
[2024-09-04T14:36:21.209Z] error: <httpProxy> Error calling http://192.168.0.9/api/v2/status/interfaces...
[2024-09-04T14:36:21.219Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.6/node_modules/follow-redirects/index.js:95:17)
      at Object.onceWrapper (node:events:632:26)
      ... 2 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.6/node_modules/follow-redirects/index.js:326:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.6/node_modules/follow-redirects/index.js:483:8)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.6/node_modules/follow-redirects/index.js:91:12)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]
[2024-09-04T14:36:21.230Z] error: <httpProxy> Error calling http://192.168.0.9/api/v2/status/system...
[2024-09-04T14:36:21.233Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.6/node_modules/follow-redirects/index.js:95:17)
      at Object.onceWrapper (node:events:632:26)
      ... 2 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.6/node_modules/follow-redirects/index.js:326:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.6/node_modules/follow-redirects/index.js:483:8)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.6/node_modules/follow-redirects/index.js:91:12)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]
[2024-09-04T14:37:01.600Z] error: <httpProxy> Error calling http://192.168.0.9/api/v2/status/interfaces...
[2024-09-04T14:37:01.605Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.6/node_modules/follow-redirects/index.js:95:17)
      at Object.onceWrapper (node:events:632:26)
      ... 2 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.6/node_modules/follow-redirects/index.js:326:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.6/node_modules/follow-redirects/index.js:483:8)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.6/node_modules/follow-redirects/index.js:91:12)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]
[2024-09-04T14:37:01.612Z] error: <httpProxy> Error calling http://192.168.0.9/api/v2/status/system...
[2024-09-04T14:37:01.616Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.6/node_modules/follow-redirects/index.js:95:17)
      at Object.onceWrapper (node:events:632:26)
      ... 2 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.6/node_modules/follow-redirects/index.js:326:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.6/node_modules/follow-redirects/index.js:483:8)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.6/node_modules/follow-redirects/index.js:91:12)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]
[2024-09-04T14:41:50.699Z] error: <httpProxy> Error calling http://192.168.0.9:8443/api/v2/status/system...
[2024-09-04T14:41:50.703Z] error: <httpProxy> [
  500,
  Error: connect ETIMEDOUT 192.168.0.9:8443
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '192.168.0.9',
    port: 8443
  }
]
[2024-09-04T14:41:50.706Z] error: <httpProxy> Error calling http://192.168.0.9:8443/api/v2/status/interfaces...
[2024-09-04T14:41:50.708Z] error: <httpProxy> [
  500,
  Error: connect ETIMEDOUT 192.168.0.9:8443
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '192.168.0.9',
    port: 8443
  }
]
[2024-09-04T14:41:50.712Z] error: <httpProxy> Error calling http://192.168.0.9:8443/api/v2/status/interfaces...
[2024-09-04T14:41:50.714Z] error: <httpProxy> [
  500,
  Error: connect ETIMEDOUT 192.168.0.9:8443
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '192.168.0.9',
    port: 8443
  }
]
[2024-09-04T14:41:50.718Z] error: <httpProxy> Error calling http://192.168.0.9:8443/api/v2/status/system...
[2024-09-04T14:41:50.720Z] error: <httpProxy> [
  500,
  Error: connect ETIMEDOUT 192.168.0.9:8443
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '192.168.0.9',
    port: 8443
  }
]
[2024-09-04T14:54:49.006Z] error: <servicesProxy> YAMLException: bad indentation of a mapping entry (54:5)

 51 |         href: http://10.1.1.11:8096
 52 |         description: Jellyfin
 53 |         icon: jellyfin
 54 |     widget:
----------^
 55 |         type: jellyfin
 56 |         url: http://10.1.1.11
    at generateError (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:1273:10)
    at throwError (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:1277:9)
    at readBlockMapping (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2272:7)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2531:12)
    at readBlockSequence (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2098:5)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2530:12)
    at readDocument (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2715:3)
    at loadDocuments (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2778:5)
    at Object.load$1 [as load] (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2804:19)
    at servicesFromConfig (/app/.next/server/chunks/5318.js:115:68)
[2024-09-04T14:54:49.031Z] error: Failed to load services.yaml, please check for errors
[2024-09-04T14:54:49.033Z] error: YAMLException: bad indentation of a mapping entry (54:5)

 51 |         href: http://10.1.1.11:8096
 52 |         description: Jellyfin
 53 |         icon: jellyfin
 54 |     widget:
----------^
 55 |         type: jellyfin
 56 |         url: http://10.1.1.11
[2024-09-04T14:54:49.039Z] error: <servicesProxy> YAMLException: bad indentation of a mapping entry (54:5)

 51 |         href: http://10.1.1.11:8096
 52 |         description: Jellyfin
 53 |         icon: jellyfin
 54 |     widget:
----------^
 55 |         type: jellyfin
 56 |         url: http://10.1.1.11
    at generateError (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:1273:10)
    at throwError (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:1277:9)
    at readBlockMapping (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2272:7)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2531:12)
    at readBlockSequence (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2098:5)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2530:12)
    at readDocument (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2715:3)
    at loadDocuments (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2778:5)
    at Object.load$1 [as load] (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2804:19)
    at servicesFromConfig (/app/.next/server/chunks/5318.js:115:68)
[2024-09-04T14:54:49.042Z] error: <servicesProxy> YAMLException: bad indentation of a mapping entry (54:5)

 51 |         href: http://10.1.1.11:8096
 52 |         description: Jellyfin
 53 |         icon: jellyfin
 54 |     widget:
----------^
 55 |         type: jellyfin
 56 |         url: http://10.1.1.11
    at generateError (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:1273:10)
    at throwError (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:1277:9)
    at readBlockMapping (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2272:7)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2531:12)
    at readBlockSequence (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2098:5)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2530:12)
    at readDocument (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2715:3)
    at loadDocuments (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2778:5)
    at Object.load$1 [as load] (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2804:19)
    at servicesFromConfig (/app/.next/server/chunks/5318.js:115:68)
[2024-09-04T14:54:49.046Z] error: <servicesProxy> YAMLException: bad indentation of a mapping entry (54:5)

 51 |         href: http://10.1.1.11:8096
 52 |         description: Jellyfin
 53 |         icon: jellyfin
 54 |     widget:
----------^
 55 |         type: jellyfin
 56 |         url: http://10.1.1.11
    at generateError (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:1273:10)
    at throwError (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:1277:9)
    at readBlockMapping (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2272:7)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2531:12)
    at readBlockSequence (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2098:5)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2530:12)
    at readDocument (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2715:3)
    at loadDocuments (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2778:5)
    at Object.load$1 [as load] (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2804:19)
    at servicesFromConfig (/app/.next/server/chunks/5318.js:115:68)
[2024-09-04T14:54:49.049Z] error: <servicesProxy> YAMLException: bad indentation of a mapping entry (54:5)

 51 |         href: http://10.1.1.11:8096
 52 |         description: Jellyfin
 53 |         icon: jellyfin
 54 |     widget:
----------^
 55 |         type: jellyfin
 56 |         url: http://10.1.1.11
    at generateError (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:1273:10)
    at throwError (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:1277:9)
    at readBlockMapping (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2272:7)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2531:12)
    at readBlockSequence (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2098:5)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2530:12)
    at readDocument (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2715:3)
    at loadDocuments (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2778:5)
    at Object.load$1 [as load] (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2804:19)
    at servicesFromConfig (/app/.next/server/chunks/5318.js:115:68)
[2024-09-04T14:54:49.055Z] error: <servicesProxy> YAMLException: bad indentation of a mapping entry (54:5)

 51 |         href: http://10.1.1.11:8096
 52 |         description: Jellyfin
 53 |         icon: jellyfin
 54 |     widget:
----------^
 55 |         type: jellyfin
 56 |         url: http://10.1.1.11
    at generateError (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:1273:10)
    at throwError (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:1277:9)
    at readBlockMapping (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2272:7)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2531:12)
    at readBlockSequence (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2098:5)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2530:12)
    at readDocument (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2715:3)
    at loadDocuments (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2778:5)
    at Object.load$1 [as load] (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2804:19)
    at servicesFromConfig (/app/.next/server/chunks/5318.js:115:68)
[2024-09-04T14:54:49.098Z] error: <servicesProxy> YAMLException: bad indentation of a mapping entry (54:5)

 51 |         href: http://10.1.1.11:8096
 52 |         description: Jellyfin
 53 |         icon: jellyfin
 54 |     widget:
----------^
 55 |         type: jellyfin
 56 |         url: http://10.1.1.11
    at generateError (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:1273:10)
    at throwError (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:1277:9)
    at readBlockMapping (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2272:7)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2531:12)
    at readBlockSequence (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2098:5)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2530:12)
    at readDocument (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2715:3)
    at loadDocuments (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2778:5)
    at Object.load$1 [as load] (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2804:19)
    at servicesFromConfig (/app/.next/server/chunks/5318.js:115:68)
[2024-09-04T14:54:49.105Z] error: <servicesProxy> YAMLException: bad indentation of a mapping entry (54:5)

 51 |         href: http://10.1.1.11:8096
 52 |         description: Jellyfin
 53 |         icon: jellyfin
 54 |     widget:
----------^
 55 |         type: jellyfin
 56 |         url: http://10.1.1.11
    at generateError (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:1273:10)
    at throwError (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:1277:9)
    at readBlockMapping (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2272:7)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2531:12)
    at readBlockSequence (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2098:5)
    at composeNode (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2530:12)
    at readDocument (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2715:3)
    at loadDocuments (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2778:5)
    at Object.load$1 [as load] (file:///app/node_modules/.pnpm/js-yaml@4.1.0/node_modules/js-yaml/dist/js-yaml.mjs:2804:19)
    at servicesFromConfig (/app/.next/server/chunks/5318.js:115:68)
[2024-09-04T14:54:49.116Z] error: Failed to load services.yaml, please check for errors
[2024-09-04T14:54:49.118Z] error: YAMLException: bad indentation of a mapping entry (54:5)

 51 |         href: http://10.1.1.11:8096
 52 |         description: Jellyfin
 53 |         icon: jellyfin
 54 |     widget:
----------^
 55 |         type: jellyfin
 56 |         url: http://10.1.1.11
[2024-09-04T14:54:49.584Z] error: Failed to load services.yaml, please check for errors
[2024-09-04T14:54:49.587Z] error: YAMLException: bad indentation of a mapping entry (54:5)

 51 |         href: http://10.1.1.11:8096
 52 |         description: Jellyfin
 53 |         icon: jellyfin
 54 |     widget:
----------^
 55 |         type: jellyfin
 56 |         url: http://10.1.1.11
[2024-09-04T14:54:58.922Z] error: <httpProxy> Error calling http://10.1.1.11/emby/Sessions...
[2024-09-04T14:54:58.932Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 10.1.1.11:80
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '10.1.1.11',
    port: 80
  }
]
[2024-09-04T14:54:58.936Z] error: <httpProxy> Error calling http://10.1.1.11/emby/Items/Counts...
[2024-09-04T14:54:58.939Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 10.1.1.11:80
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '10.1.1.11',
    port: 80
  }
]
[2024-09-04T14:55:04.058Z] error: <httpProxy> Error calling http://10.1.1.11/emby/Sessions...
[2024-09-04T14:55:04.061Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 10.1.1.11:80
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '10.1.1.11',
    port: 80
  }
]
[2024-09-04T14:55:09.381Z] error: <httpProxy> Error calling http://10.1.1.11/emby/Sessions...
[2024-09-04T14:55:09.385Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 10.1.1.11:80
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '10.1.1.11',
    port: 80
  }
]
[2024-09-04T14:55:14.423Z] error: <httpProxy> Error calling http://10.1.1.11/emby/Sessions...
[2024-09-04T14:55:14.426Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 10.1.1.11:80
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '10.1.1.11',
    port: 80
  }
]
[2024-09-04T14:55:19.457Z] error: <httpProxy> Error calling http://10.1.1.11/emby/Sessions...
[2024-09-04T14:55:19.461Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 10.1.1.11:80
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '10.1.1.11',
    port: 80
  }
]
[2024-09-04T14:55:21.049Z] error: <httpProxy> Error calling http://10.1.1.11/emby/Items/Counts...
[2024-09-04T14:55:21.051Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 10.1.1.11:80
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '10.1.1.11',
    port: 80
  }
]
[2024-09-04T14:55:37.094Z] error: <httpProxy> Error calling http://10.1.1.11/emby/Sessions...
[2024-09-04T14:55:37.097Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 10.1.1.11:80
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '10.1.1.11',
    port: 80
  }
]
[2024-09-04T14:55:37.113Z] error: <httpProxy> Error calling http://10.1.1.11/emby/Items/Counts...
[2024-09-04T14:55:37.115Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 10.1.1.11:80
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '10.1.1.11',
    port: 80
  }
]
[2024-09-04T14:55:40.399Z] error: <httpProxy> Error calling http://10.1.1.11/emby/Sessions...
[2024-09-04T14:55:40.403Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 10.1.1.11:80
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '10.1.1.11',
    port: 80
  }
]
[2024-09-04T14:55:45.432Z] error: <httpProxy> Error calling http://10.1.1.11/emby/Sessions...
[2024-09-04T14:55:45.437Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 10.1.1.11:80
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '10.1.1.11',
    port: 80
  }
]
[2024-09-04T14:55:50.470Z] error: <httpProxy> Error calling http://10.1.1.11/emby/Sessions...
[2024-09-04T14:55:50.473Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 10.1.1.11:80
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '10.1.1.11',
    port: 80
  }
]
[2024-09-04T14:55:55.507Z] error: <httpProxy> Error calling http://10.1.1.11/emby/Sessions...
[2024-09-04T14:55:55.509Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 10.1.1.11:80
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '10.1.1.11',
    port: 80
  }
]
[2024-09-04T14:55:59.049Z] error: <httpProxy> Error calling http://10.1.1.11/emby/Items/Counts...
[2024-09-04T14:55:59.051Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 10.1.1.11:80
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '10.1.1.11',
    port: 80
  }
]
[2024-09-04T14:56:00.550Z] error: <httpProxy> Error calling http://10.1.1.11/emby/Sessions...
[2024-09-04T14:56:00.552Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 10.1.1.11:80
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '10.1.1.11',
    port: 80
  }
]
[2024-09-04T14:56:05.595Z] error: <httpProxy> Error calling http://10.1.1.11/emby/Sessions...
[2024-09-04T14:56:05.596Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 10.1.1.11:80
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '10.1.1.11',
    port: 80
  }
]
[2024-09-04T14:56:10.623Z] error: <httpProxy> Error calling http://10.1.1.11/emby/Sessions...
[2024-09-04T14:56:10.625Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 10.1.1.11:80
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '10.1.1.11',
    port: 80
  }
]
[2024-09-04T14:56:15.765Z] error: <httpProxy> Error calling http://10.1.1.11/emby/Sessions...
[2024-09-04T14:56:15.766Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 10.1.1.11:80
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '10.1.1.11',
    port: 80
  }
]
[2024-09-04T14:56:20.886Z] error: <httpProxy> Error calling http://10.1.1.11/emby/Sessions...
[2024-09-04T14:56:20.887Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 10.1.1.11:80
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '10.1.1.11',
    port: 80
  }
]
[2024-09-04T14:56:25.923Z] error: <httpProxy> Error calling http://10.1.1.11/emby/Sessions...
[2024-09-04T14:56:25.925Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 10.1.1.11:80
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '10.1.1.11',
    port: 80
  }
]
[2024-09-04T14:56:30.961Z] error: <httpProxy> Error calling http://10.1.1.11/emby/Sessions...
[2024-09-04T14:56:30.962Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 10.1.1.11:80
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '10.1.1.11',
    port: 80
  }
]
[2024-09-04T14:56:36.018Z] error: <httpProxy> Error calling http://10.1.1.11/emby/Sessions...
[2024-09-04T14:56:36.021Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 10.1.1.11:80
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '10.1.1.11',
    port: 80
  }
]
[2024-09-04T14:56:41.090Z] error: <httpProxy> Error calling http://10.1.1.11/emby/Sessions...
[2024-09-04T14:56:41.093Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 10.1.1.11:80
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '10.1.1.11',
    port: 80
  }
]
[2024-09-04T14:56:46.210Z] error: <httpProxy> Error calling http://10.1.1.11/emby/Sessions...
[2024-09-04T14:56:46.213Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 10.1.1.11:80
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '10.1.1.11',
    port: 80
  }
]
[2024-09-04T14:56:49.228Z] error: <httpProxy> Error calling http://10.1.1.11/emby/Sessions...
[2024-09-04T14:56:49.231Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 10.1.1.11:80
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '10.1.1.11',
    port: 80
  }
]
[2024-09-04T14:56:49.258Z] error: <httpProxy> Error calling http://10.1.1.11/emby/Items/Counts...
[2024-09-04T14:56:49.261Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 10.1.1.11:80
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '10.1.1.11',
    port: 80
  }
]
[2024-09-04T14:56:50.124Z] error: <httpProxy> Error calling http://10.1.1.11/emby/Sessions...
[2024-09-04T14:56:50.125Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 10.1.1.11:80
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '10.1.1.11',
    port: 80
  }
]
[2024-09-04T14:56:50.156Z] error: <httpProxy> Error calling http://10.1.1.11/emby/Items/Counts...
[2024-09-04T14:56:50.158Z] error: <httpProxy> [
  500,
  Error: connect ECONNREFUSED 10.1.1.11:80
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '10.1.1.11',
    port: 80
  }
]
[2024-09-04T15:09:09.611Z] error: <credentialedProxyHandler> HTTP Error 404 calling https://192.168.0.12:9443/api/endpoints/1/docker/containers/json?all=1
[2024-09-04T15:09:20.591Z] error: <credentialedProxyHandler> HTTP Error 404 calling https://192.168.0.12:9443/api/endpoints/1/docker/containers/json?all=1
[2024-09-04T15:12:44.747Z] error: <httpProxy> Error calling https://10.1.1.11:8096/...
[2024-09-04T15:12:44.749Z] error: <httpProxy> [
  500,
  Error: write EPROTO D819AE71A57C0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
  
      at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16) {
    errno: -71,
    code: 'EPROTO',
    syscall: 'write'
  }
]
[2024-09-04T15:12:44.759Z] error: <httpProxy> Error calling https://10.1.1.11:8096/...
[2024-09-04T15:12:44.760Z] error: <httpProxy> [
  500,
  Error: write EPROTO D819AE71A57C0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
  
      at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16) {
    errno: -71,
    code: 'EPROTO',
    syscall: 'write'
  }
]
[2024-09-04T15:13:08.492Z] error: <httpProxy> Error calling https://10.1.1.11:8096/...
[2024-09-04T15:13:08.495Z] error: <httpProxy> [
  500,
  Error: write EPROTO D819AE71A57C0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
  
      at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16) {
    errno: -71,
    code: 'EPROTO',
    syscall: 'write'
  }
]
[2024-09-04T15:13:08.506Z] error: <httpProxy> Error calling https://10.1.1.11:8096/...
[2024-09-04T15:13:08.508Z] error: <httpProxy> [
  500,
  Error: write EPROTO D819AE71A57C0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
  
      at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16) {
    errno: -71,
    code: 'EPROTO',
    syscall: 'write'
  }
]
[2024-09-04T15:13:09.651Z] error: <httpProxy> Error calling https://10.1.1.11:8096/...
[2024-09-04T15:13:09.653Z] error: <httpProxy> [
  500,
  Error: write EPROTO D819AE71A57C0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
  
      at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16) {
    errno: -71,
    code: 'EPROTO',
    syscall: 'write'
  }
]
[2024-09-04T15:13:09.679Z] error: <httpProxy> Error calling https://10.1.1.11:8096/...
[2024-09-04T15:13:09.681Z] error: <httpProxy> [
  500,
  Error: write EPROTO D819AE71A57C0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
  
      at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16) {
    errno: -71,
    code: 'EPROTO',
    syscall: 'write'
  }
]
[2024-09-04T15:57:51.591Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.0.10:8006/api2/json/cluster/resources
[2024-09-04T15:57:52.784Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.0.10:8006/api2/json/cluster/resources
[2024-09-04T15:58:00.934Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.0.10:8006/api2/json/cluster/resources
[2024-09-04T15:58:05.518Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.0.10:8006/api2/json/cluster/resources
[2024-09-04T15:58:06.485Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.0.10:8006/api2/json/cluster/resources
[2024-09-04T15:58:15.425Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.0.10:8006/api2/json/cluster/resources
[2024-09-04T15:58:56.023Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.0.10:8006/api2/json/cluster/resources
[2024-09-04T15:59:04.121Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.0.10:8006/api2/json/cluster/resources
[2024-09-04T15:59:21.214Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.0.10:8006/api2/json/cluster/resources
[2024-09-04T15:59:29.261Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.0.10:8006/api2/json/cluster/resources
[2024-09-04T15:59:42.313Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.0.10:8006/api2/json/cluster/resources
[2024-09-04T16:00:03.112Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.0.10:8006/api2/json/cluster/resources
[2024-09-04T16:00:11.158Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.0.10:8006/api2/json/cluster/resources
[2024-09-04T16:00:18.046Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.0.10:8006/api2/json/cluster/resources
[2024-09-04T16:00:24.423Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.0.10:8006/api2/json/cluster/resources
[2024-09-04T16:00:31.109Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.0.10:8006/api2/json/cluster/resources
[2024-09-04T16:00:54.168Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.0.10:8006/api2/json/cluster/resources
[2024-09-04T16:00:57.516Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.0.10:8006/api2/json/cluster/resources
[2024-09-04T16:01:52.262Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.0.10:8006/api2/json/cluster/resources
[2024-09-04T16:02:09.817Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.0.10:8006/api2/json/cluster/resources
[2024-09-04T16:02:10.863Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.0.10:8006/api2/json/cluster/resources
[2024-09-04T16:02:21.670Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.0.10:8006/api2/json/cluster/resources
[2024-09-04T16:02:22.387Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.0.10:8006/api2/json/cluster/resources
[2024-09-04T16:02:35.430Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.0.10:8006/api2/json/cluster/resources
[2024-09-04T16:02:39.113Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.0.10:8006/api2/json/cluster/resources
[2024-09-04T16:02:59.403Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.0.10:8006/api2/json/cluster/resources
[2024-09-04T16:04:08.193Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.0.10:8006/api2/json/cluster/resources
[2024-09-04T16:04:16.234Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.0.10:8006/api2/json/cluster/resources
[2024-09-04T16:04:34.278Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.0.10:8006/api2/json/cluster/resources
[2024-09-04T16:05:22.363Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.0.10:8006/api2/json/cluster/resources
[2024-09-04T16:06:30.401Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.0.10:8006/api2/json/cluster/resources
[2024-09-04T16:08:13.448Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.0.10:8006/api2/json/cluster/resources
[2024-09-04T16:09:55.838Z] error: <httpProxy> Error calling https://{{homepage_var_wattmonster_ip}}:8006/...
[2024-09-04T16:09:55.846Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN {{homepage_var_wattmonster_ip}}
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '{{homepage_var_wattmonster_ip}}'
  }
]
[2024-09-04T16:10:00.855Z] error: <httpProxy> Error calling https://{{homepage_var_wattmonster_ip}}:8006/...
[2024-09-04T16:10:00.856Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN {{homepage_var_wattmonster_ip}}
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '{{homepage_var_wattmonster_ip}}'
  }
]
[2024-09-04T16:10:35.894Z] error: <httpProxy> Error calling https://{{homepage_var_wattmonster_ip}}:8006/...
[2024-09-04T16:10:35.896Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN {{homepage_var_wattmonster_ip}}
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '{{homepage_var_wattmonster_ip}}'
  }
]
[2024-09-04T16:10:40.905Z] error: <httpProxy> Error calling https://{{homepage_var_wattmonster_ip}}:8006/...
[2024-09-04T16:10:40.908Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN {{homepage_var_wattmonster_ip}}
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '{{homepage_var_wattmonster_ip}}'
  }
]
[2024-09-04T16:10:57.167Z] error: <httpProxy> Error calling https://{{homepage_var_crafty_ip}}:8443/...
[2024-09-04T16:10:57.169Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN {{homepage_var_crafty_ip}}
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '{{homepage_var_crafty_ip}}'
  }
]
[2024-09-04T16:11:02.180Z] error: <httpProxy> Error calling https://{{homepage_var_crafty_ip}}:8443/...
[2024-09-04T16:11:02.182Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN {{homepage_var_crafty_ip}}
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '{{homepage_var_crafty_ip}}'
  }
]
[2024-09-04T16:11:22.426Z] error: <httpProxy> Error calling https://{{homepage_var_wattmonster_ip}}:8006/...
[2024-09-04T16:11:22.429Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN {{homepage_var_wattmonster_ip}}
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '{{homepage_var_wattmonster_ip}}'
  }
]
[2024-09-04T16:11:22.448Z] error: <httpProxy> Error calling https://}:8006/api2/json/cluster/resources...
[2024-09-04T16:11:22.452Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:11:22.453Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://}:8006/api2/json/cluster/resources
[2024-09-04T16:11:27.436Z] error: <httpProxy> Error calling http://}/api/v2.0/system/info...
[2024-09-04T16:11:27.440Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:11:27.442Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://}/api/v2.0/system/info
[2024-09-04T16:11:27.470Z] error: <httpProxy> Error calling https://}/api/v2/status/interfaces...
[2024-09-04T16:11:27.472Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:11:32.439Z] error: <httpProxy> Error calling https://}/api/v2/status/system...
[2024-09-04T16:11:32.444Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:11:32.460Z] error: <httpProxy> Error calling http://}/api/v2.0/alert/list...
[2024-09-04T16:11:32.462Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:11:32.462Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://}/api/v2.0/alert/list
[2024-09-04T16:11:37.442Z] error: <httpProxy> Error calling https://{{homepage_var_wattmonster_ip}}:8006/...
[2024-09-04T16:11:37.446Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN {{homepage_var_wattmonster_ip}}
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '{{homepage_var_wattmonster_ip}}'
  }
]
[2024-09-04T16:11:37.465Z] error: <httpProxy> Error calling http://}/api/v2.0/pool...
[2024-09-04T16:11:37.470Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:11:37.472Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://}/api/v2.0/pool
[2024-09-04T16:11:37.489Z] error: <minecraftProxyHandler> Error: Timed out (10 seconds passed)
    at Timeout._onTimeout (/app/node_modules/.pnpm/minecraft-ping-js@1.0.2/node_modules/minecraft-ping-js/index.js:67:20)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
[2024-09-04T16:11:37.547Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.0.12:9443/api/endpoints/2/docker/containers/json?all=1
[2024-09-04T16:11:40.520Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.0.10:8006/api2/json/cluster/resources
[2024-09-04T16:11:42.450Z] error: <httpProxy> Error calling https://{{homepage_var_crafty_ip}}:8443/...
[2024-09-04T16:11:42.453Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN {{homepage_var_crafty_ip}}
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '{{homepage_var_crafty_ip}}'
  }
]
[2024-09-04T16:11:47.457Z] error: <httpProxy> Error calling http://}:8096/emby/Sessions...
[2024-09-04T16:11:47.460Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:11:47.477Z] error: <httpProxy> Error calling http://}:8096/emby/Items/Counts...
[2024-09-04T16:11:47.480Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:11:52.473Z] error: <httpProxy> Error calling https://{{homepage_var_wattmonster_ip}}:8006/...
[2024-09-04T16:11:52.479Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN {{homepage_var_wattmonster_ip}}
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '{{homepage_var_wattmonster_ip}}'
  }
]
[2024-09-04T16:11:52.498Z] error: <httpProxy> Error calling https://}:8006/api2/json/cluster/resources...
[2024-09-04T16:11:52.502Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:11:52.506Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://}:8006/api2/json/cluster/resources
[2024-09-04T16:11:57.478Z] error: <httpProxy> Error calling https://}/api/v2/status/system...
[2024-09-04T16:11:57.483Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:11:57.503Z] error: <httpProxy> Error calling https://}/api/v2/status/interfaces...
[2024-09-04T16:11:57.505Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:12:02.485Z] error: <httpProxy> Error calling http://}/api/v2.0/alert/list...
[2024-09-04T16:12:02.488Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:12:02.490Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://}/api/v2.0/alert/list
[2024-09-04T16:12:02.503Z] error: <httpProxy> Error calling http://}/api/v2.0/system/info...
[2024-09-04T16:12:02.506Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:12:02.508Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://}/api/v2.0/system/info
[2024-09-04T16:12:07.491Z] error: <httpProxy> Error calling https://{{homepage_var_crafty_ip}}:8443/...
[2024-09-04T16:12:07.495Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN {{homepage_var_crafty_ip}}
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '{{homepage_var_crafty_ip}}'
  }
]
[2024-09-04T16:12:07.508Z] error: <httpProxy> Error calling https://{{homepage_var_wattmonster_ip}}:8006/...
[2024-09-04T16:12:07.511Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN {{homepage_var_wattmonster_ip}}
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '{{homepage_var_wattmonster_ip}}'
  }
]
[2024-09-04T16:12:07.517Z] error: <minecraftProxyHandler> Error: Timed out (10 seconds passed)
    at Timeout._onTimeout (/app/node_modules/.pnpm/minecraft-ping-js@1.0.2/node_modules/minecraft-ping-js/index.js:67:20)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
[2024-09-04T16:12:07.615Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.0.12:9443/api/endpoints/2/docker/containers/json?all=1
[2024-09-04T16:12:10.556Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.0.10:8006/api2/json/cluster/resources
[2024-09-04T16:12:12.494Z] error: <httpProxy> Error calling http://}/api/v2.0/pool...
[2024-09-04T16:12:12.497Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:12:12.499Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://}/api/v2.0/pool
[2024-09-04T16:12:12.514Z] error: <httpProxy> Error calling https://{{homepage_var_crafty_ip}}:8443/...
[2024-09-04T16:12:12.517Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN {{homepage_var_crafty_ip}}
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '{{homepage_var_crafty_ip}}'
  }
]
[2024-09-04T16:12:17.520Z] error: <httpProxy> Error calling http://}:8096/emby/Sessions...
[2024-09-04T16:12:17.524Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:12:22.503Z] error: <httpProxy> Error calling http://}:8096/emby/Items/Counts...
[2024-09-04T16:12:22.507Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:12:22.525Z] error: <httpProxy> Error calling https://{{homepage_var_crafty_ip}}:8443/...
[2024-09-04T16:12:22.526Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN {{homepage_var_crafty_ip}}
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '{{homepage_var_crafty_ip}}'
  }
]
[2024-09-04T16:12:27.508Z] error: <httpProxy> Error calling https://}:8006/api2/json/cluster/resources...
[2024-09-04T16:12:27.512Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:12:27.512Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://}:8006/api2/json/cluster/resources
[2024-09-04T16:12:27.702Z] error: <httpProxy> Error calling http://}:8096/emby/Sessions...
[2024-09-04T16:12:27.704Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:12:37.736Z] error: <httpProxy> Error calling http://}:8096/emby/Sessions...
[2024-09-04T16:12:37.739Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:12:43.186Z] error: <httpProxy> Error calling https://{{homepage_var_wattmonster_ip}}:8006/...
[2024-09-04T16:12:43.189Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN {{homepage_var_wattmonster_ip}}
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '{{homepage_var_wattmonster_ip}}'
  }
]
[2024-09-04T16:12:43.200Z] error: <httpProxy> Error calling https://{{homepage_var_wattmorpheus_ip}}:8006/...
[2024-09-04T16:12:43.202Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN {{homepage_var_wattmorpheus_ip}}
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '{{homepage_var_wattmorpheus_ip}}'
  }
]
[2024-09-04T16:12:48.192Z] error: <httpProxy> Error calling http://}:8096/emby/Sessions...
[2024-09-04T16:12:48.196Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:12:48.203Z] error: <httpProxy> Error calling https://{{homepage_var_wattmonster_ip}}:8006/...
[2024-09-04T16:12:48.205Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN {{homepage_var_wattmonster_ip}}
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '{{homepage_var_wattmonster_ip}}'
  }
]
[2024-09-04T16:12:53.196Z] error: <httpProxy> Error calling https://{{homepage_var_wattmorpheus_ip}}:8006/...
[2024-09-04T16:12:53.199Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN {{homepage_var_wattmorpheus_ip}}
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '{{homepage_var_wattmorpheus_ip}}'
  }
]
[2024-09-04T16:12:57.586Z] error: <httpProxy> Error calling https://{{homepage_var_crafty_ip}}:8443/...
[2024-09-04T16:12:57.589Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN {{homepage_var_crafty_ip}}
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '{{homepage_var_crafty_ip}}'
  }
]
[2024-09-04T16:12:58.283Z] error: <httpProxy> Error calling http://}:8096/emby/Sessions...
[2024-09-04T16:12:58.285Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:13:02.599Z] error: <httpProxy> Error calling https://{{homepage_var_crafty_ip}}:8443/...
[2024-09-04T16:13:02.600Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN {{homepage_var_crafty_ip}}
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '{{homepage_var_crafty_ip}}'
  }
]
[2024-09-04T16:13:08.320Z] error: <httpProxy> Error calling http://}:8096/emby/Sessions...
[2024-09-04T16:13:08.322Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:13:12.751Z] error: <httpProxy> Error calling http://}:8096/emby/Items/Counts...
[2024-09-04T16:13:12.754Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:13:18.377Z] error: <httpProxy> Error calling http://}:8096/emby/Sessions...
[2024-09-04T16:13:18.380Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:13:23.232Z] error: <httpProxy> Error calling https://{{homepage_var_wattmonster_ip}}:8006/...
[2024-09-04T16:13:23.234Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN {{homepage_var_wattmonster_ip}}
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '{{homepage_var_wattmonster_ip}}'
  }
]
[2024-09-04T16:13:28.245Z] error: <httpProxy> Error calling https://{{homepage_var_wattmonster_ip}}:8006/...
[2024-09-04T16:13:28.248Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN {{homepage_var_wattmonster_ip}}
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '{{homepage_var_wattmonster_ip}}'
  }
]
[2024-09-04T16:13:28.287Z] error: <httpProxy> Error calling https://{{homepage_var_wattmorpheus_ip}}:8006/...
[2024-09-04T16:13:28.289Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN {{homepage_var_wattmorpheus_ip}}
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '{{homepage_var_wattmorpheus_ip}}'
  }
]
[2024-09-04T16:13:33.251Z] error: <httpProxy> Error calling http://}:8096/emby/Sessions...
[2024-09-04T16:13:33.254Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:13:33.297Z] error: <httpProxy> Error calling https://{{homepage_var_wattmorpheus_ip}}:8006/...
[2024-09-04T16:13:33.299Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN {{homepage_var_wattmorpheus_ip}}
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '{{homepage_var_wattmorpheus_ip}}'
  }
]
[2024-09-04T16:13:38.255Z] error: <httpProxy> Error calling https://{{homepage_var_crafty_ip}}:8443/...
[2024-09-04T16:13:38.258Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN {{homepage_var_crafty_ip}}
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '{{homepage_var_crafty_ip}}'
  }
]
[2024-09-04T16:13:43.266Z] error: <httpProxy> Error calling https://{{homepage_var_crafty_ip}}:8443/...
[2024-09-04T16:13:43.267Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN {{homepage_var_crafty_ip}}
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '{{homepage_var_crafty_ip}}'
  }
]
[2024-09-04T16:13:43.297Z] error: <httpProxy> Error calling http://}:8096/emby/Sessions...
[2024-09-04T16:13:43.298Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:13:53.332Z] error: <httpProxy> Error calling http://}:8096/emby/Sessions...
[2024-09-04T16:13:53.333Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:14:03.277Z] error: <httpProxy> Error calling https://{{homepage_var_wattmonster_ip}}:8006/...
[2024-09-04T16:14:03.278Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN {{homepage_var_wattmonster_ip}}
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '{{homepage_var_wattmonster_ip}}'
  }
]
[2024-09-04T16:14:03.371Z] error: <httpProxy> Error calling http://}:8096/emby/Sessions...
[2024-09-04T16:14:03.373Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:14:08.288Z] error: <httpProxy> Error calling https://{{homepage_var_wattmonster_ip}}:8006/...
[2024-09-04T16:14:08.290Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN {{homepage_var_wattmonster_ip}}
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '{{homepage_var_wattmonster_ip}}'
  }
]
[2024-09-04T16:14:08.374Z] error: <httpProxy> Error calling https://{{homepage_var_wattmorpheus_ip}}:8006/...
[2024-09-04T16:14:08.375Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN {{homepage_var_wattmorpheus_ip}}
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '{{homepage_var_wattmorpheus_ip}}'
  }
]
[2024-09-04T16:14:13.384Z] error: <httpProxy> Error calling https://{{homepage_var_wattmorpheus_ip}}:8006/...
[2024-09-04T16:14:13.388Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN {{homepage_var_wattmorpheus_ip}}
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '{{homepage_var_wattmorpheus_ip}}'
  }
]
[2024-09-04T16:14:13.397Z] error: <httpProxy> Error calling http://}:8096/emby/Sessions...
[2024-09-04T16:14:13.400Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:14:18.386Z] error: <httpProxy> Error calling http://}:8096/emby/Items/Counts...
[2024-09-04T16:14:18.388Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:14:18.401Z] error: <httpProxy> Error calling https://{{homepage_var_crafty_ip}}:8443/...
[2024-09-04T16:14:18.402Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN {{homepage_var_crafty_ip}}
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '{{homepage_var_crafty_ip}}'
  }
]
[2024-09-04T16:14:23.410Z] error: <httpProxy> Error calling https://{{homepage_var_crafty_ip}}:8443/...
[2024-09-04T16:14:23.412Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN {{homepage_var_crafty_ip}}
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '{{homepage_var_crafty_ip}}'
  }
]
[2024-09-04T16:14:23.426Z] error: <httpProxy> Error calling http://}:8096/emby/Sessions...
[2024-09-04T16:14:23.428Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:14:31.996Z] error: <httpProxy> Error calling https://{{homepage_var_wattmonster_ip}}:8006/...
[2024-09-04T16:14:32.000Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN {{homepage_var_wattmonster_ip}}
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '{{homepage_var_wattmonster_ip}}'
  }
]
[2024-09-04T16:14:32.018Z] error: <httpProxy> Error calling https://{{homepage_var_crafty_ip}}:8443/...
[2024-09-04T16:14:32.021Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN {{homepage_var_crafty_ip}}
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '{{homepage_var_crafty_ip}}'
  }
]
[2024-09-04T16:14:37.003Z] error: <httpProxy> Error calling https://{{homepage_var_wattmorpheus_ip}}:8006/...
[2024-09-04T16:14:37.006Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN {{homepage_var_wattmorpheus_ip}}
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '{{homepage_var_wattmorpheus_ip}}'
  }
]
[2024-09-04T16:14:37.022Z] error: <httpProxy> Error calling http://}:8096/emby/Sessions...
[2024-09-04T16:14:37.025Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:14:42.015Z] error: <httpProxy> Error calling http://}:8096/emby/Items/Counts...
[2024-09-04T16:14:42.017Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:14:42.030Z] error: <httpProxy> Error calling https://}:8006/api2/json/cluster/resources...
[2024-09-04T16:14:42.033Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:14:42.035Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://}:8006/api2/json/cluster/resources
[2024-09-04T16:14:47.023Z] error: <httpProxy> Error calling https://{{homepage_var_wattmonster_ip}}:8006/...
[2024-09-04T16:14:47.024Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN {{homepage_var_wattmonster_ip}}
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '{{homepage_var_wattmonster_ip}}'
  }
]
[2024-09-04T16:14:47.037Z] error: <httpProxy> Error calling https://{{homepage_var_crafty_ip}}:8443/...
[2024-09-04T16:14:47.040Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN {{homepage_var_crafty_ip}}
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '{{homepage_var_crafty_ip}}'
  }
]
[2024-09-04T16:14:52.026Z] error: <httpProxy> Error calling https://{{homepage_var_wattmorpheus_ip}}:8006/...
[2024-09-04T16:14:52.028Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN {{homepage_var_wattmorpheus_ip}}
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '{{homepage_var_wattmorpheus_ip}}'
  }
]
[2024-09-04T16:14:52.041Z] error: <httpProxy> Error calling https://}/api/v2/status/system...
[2024-09-04T16:14:52.043Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:14:57.027Z] error: <httpProxy> Error calling https://}/api/v2/status/interfaces...
[2024-09-04T16:14:57.030Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:14:57.048Z] error: <httpProxy> Error calling http://}/api/v2.0/alert/list...
[2024-09-04T16:14:57.051Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:14:57.052Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://}/api/v2.0/alert/list
[2024-09-04T16:15:02.034Z] error: <httpProxy> Error calling http://}/api/v2.0/system/info...
[2024-09-04T16:15:02.037Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:15:02.037Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://}/api/v2.0/system/info
[2024-09-04T16:15:02.055Z] error: <httpProxy> Error calling http://}/api/v2.0/pool...
[2024-09-04T16:15:02.059Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:15:02.061Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://}/api/v2.0/pool
[2024-09-04T16:15:02.065Z] error: <minecraftProxyHandler> Error: Timed out (10 seconds passed)
    at Timeout._onTimeout (/app/node_modules/.pnpm/minecraft-ping-js@1.0.2/node_modules/minecraft-ping-js/index.js:67:20)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
[2024-09-04T16:15:07.057Z] error: <httpProxy> Error calling https://}:8006/api2/json/cluster/resources...
[2024-09-04T16:15:07.061Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:15:07.062Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://}:8006/api2/json/cluster/resources
[2024-09-04T16:15:12.045Z] error: <httpProxy> Error calling https://}:9443/api/endpoints/2/docker/containers/json...
[2024-09-04T16:15:12.049Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:15:12.049Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://}:9443/api/endpoints/2/docker/containers/json?all=1
[2024-09-04T16:15:12.064Z] error: <httpProxy> Error calling https://{{homepage_var_wattmonster_ip}}:8006/...
[2024-09-04T16:15:12.067Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN {{homepage_var_wattmonster_ip}}
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '{{homepage_var_wattmonster_ip}}'
  }
]
[2024-09-04T16:15:17.051Z] error: <httpProxy> Error calling https://}/api/v2/status/system...
[2024-09-04T16:15:17.053Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:15:17.072Z] error: <httpProxy> Error calling https://}:8006/api2/json/cluster/resources...
[2024-09-04T16:15:17.077Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:15:17.081Z] error: <credentialedProxyHandler> HTTP Error 500 calling https://}:8006/api2/json/cluster/resources
[2024-09-04T16:15:22.057Z] error: <httpProxy> Error calling https://}/api/v2/status/interfaces...
[2024-09-04T16:15:22.060Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:15:22.076Z] error: <httpProxy> Error calling http://}/api/v2.0/alert/list...
[2024-09-04T16:15:22.079Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:15:22.081Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://}/api/v2.0/alert/list
[2024-09-04T16:15:27.064Z] error: <httpProxy> Error calling http://}/api/v2.0/system/info...
[2024-09-04T16:15:27.068Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN }
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '}'
  }
]
[2024-09-04T16:15:27.068Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://}/api/v2.0/system/info
[2024-09-04T16:15:27.082Z] error: <httpProxy> Error calling https://{{homepage_var_wattmonster_ip}}:8006/...
[2024-09-04T16:15:27.085Z] error: <httpProxy> [
  500,
  Error: getaddrinfo EAI_AGAIN {{homepage_var_wattmonster_ip}}
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '{{homepage_var_wattmonster_ip}}'
  }
]
